### PR TITLE
bugfix: Recorder is not initialized error #21

### PR DESCRIPTION
**Pull request by congpeijun**

### CODE REVIEW

**Comment by congpeijun** [comment]
#21 Fix this error.

**Comment by streamer45** [comment]
@congpeijun 

Can you share a bit more context on this PR? The linked issue was caused by a bug in the code (now fixed).
Were you having issues with the specific command this PR touches instead? I am thinking it shouldn't really matter whether we add the slash or not to the source directory, unless there's a symlink involved, which should not be the case.

**Comment by congpeijun** [comment]
Hi, @streamer45
When add the slash, the cp command  only copy the folders and files in the `public` folder,  but when realy want the whole public folder instead.
I check the plugin starter template, and It do this also.
https://github.com/mattermost/mattermost-plugin-starter-template/blob/master/Makefile#L106

**Comment by streamer45** [comment]
@congpeijun 

Thank you for added info and for the PR. I was asking because I cannot reproduce this behaviour on Linux.  
The command performs the same action with or without the ending slash. Maybe it's a shell/system related issue. 

Out of curiosity, on what operating system are you experiencing this?

**Review by streamer45 — APPROVED** [review]

**Comment by congpeijun** [comment]
@streamer45 macOS Big sur. Good news for merging, Thanks!

**Pull request merged**
